
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LayoutContainer from "@/components/LayoutContainer";
import { cn } from "@/lib/utils";
// import {ThemeProvider} from 'next-themes'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <LayoutContainer>
      <body
       className= {`${geistSans.variable} ${geistMono.variable} antialiased` }  >


          <Navbar/>
        {children}

      </body>
      </LayoutContainer>

    </html>
  );
}
